

## Introduction to Hugging Face

Hugging Face provides **state-of-the-art** NLP (and increasingly, multimodal) models and an easy-to-use Python library called **Transformers**. With just a few lines of code you can:

* **Load** pre-trained models for dozens of tasks
* **Run** inference via high-level “pipelines”
* **Fine-tune** on your own data

---

## 1. Setup in Google Colab

```bash
# Install the core libraries
!pip install transformers datasets huggingface_hub --quiet
```

> **Tip:** Colab often comes with a GPU—go to **Runtime → Change runtime type → GPU** for faster inference.

---

## 2. Quick-start with Pipelines

The `pipeline` API wraps tokenization, model loading, and inference in one object.

### 2.1 Sentiment Analysis

```python
from transformers import pipeline

# 1. Load a sentiment-analysis pipeline (defaults to a small model)
sentiment = pipeline("sentiment-analysis")

# 2. Run inference
examples = [
    "Hugging Face makes NLP super accessible!",
    "I dislike bugs in my code..."
]
results = sentiment(examples)
for text, res in zip(examples, results):
    print(f"{text!r:50} → label={res['label']}, score={res['score']:.3f}")
```

### 2.2 Text Generation

```python
from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")
prompt = "Once upon a time"
out = generator(prompt, max_length=30, num_return_sequences=1)
print(out[0]["generated_text"])
```

In [ ]:
!pip install transformers datasets huggingface_hub --quiet

In [ ]:
from transformers import pipeline

# 1. Load a sentiment-analysis pipeline (defaults to a small model)
sentiment = pipeline("sentiment-analysis")

# 2. Run inference
examples = [
    "Hugging Face makes NLP super accessible!",
    "I dislike bugs in my code..."
]
results = sentiment(examples)
for text, res in zip(examples, results):
    print(f"{text!r:50} → label={res['label']}, score={res['score']:.3f}")

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

'Hugging Face makes NLP super accessible!'         → label=POSITIVE, score=1.000
'I dislike bugs in my code...'                     → label=NEGATIVE, score=0.999

In [ ]:
from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")
prompt = "Once upon a time"
out = generator(prompt, max_length=30, num_return_sequences=1)
print(out[0]["generated_text"])

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'max_length', 'num_return_sequences'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=30) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Once upon a time, I did not know what I had done - I did not trust what I had done. I did not know how to tell the truth, to tell my friends, to tell my family all the time. I did not know how to understand the world, how to deal with the emotions of others. I did not know how to deal with the emotions of others. I did not know how to make my child happy. And by the time I was seven years old, I was too stupid to know my child had any of that.

I did not realize that I had been so wrong.

And I have to admit that my own experience has been profoundly disturbing.

I have been very lucky to have had parents who have not been so lucky.

I have been fortunate to have a father (who, if you are wondering, has actually lived through this experience) who is a very good human being, who had had lots of time together with his children, and who is now very much alive and well with his children.

I have had a father who is very, very good, a great man, and I am extremely lucky to have had a mother who has not been so lucky, and who has not been so lucky to have

# Finetuning GPT-2

*In this lab you will work on finetuning GPT 2 to solve specific problems*

- https://www.kaggle.com/code/changyeop/how-to-fine-tune-gpt-2-for-beginners
- https://medium.com/@prashanth.ramanathan/fine-tuning-a-pre-trained-gpt-2-model-and-performing-inference-a-hands-on-guide-57c097a3b810

In [ ]:
# Your Code for recreating these notebooks here

In [ ]:
# 1. Install
!pip install transformers datasets torch --quiet

# 2. Imports
from transformers import (
    GPT2Tokenizer,
    GPT2ForSequenceClassification,
    TrainingArguments,
    Trainer
)
from datasets import load_dataset

# 3. Load tokenizer (converts text <-> numbers the model understands)
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token  # GPT-2 has no pad token by default; reuse "end of text" token

# 4. Load the dataset
dataset = load_dataset("stanfordnlp/imdb")

# 5. Tokenize every example
def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

tokenized_dataset = dataset.map(tokenize_function, batched=True)

# 6. Load pre-trained GPT-2 set up for classification (2 labels: pos/neg)
model = GPT2ForSequenceClassification.from_pretrained("gpt2", num_labels=2)
model.config.pad_token_id = tokenizer.pad_token_id

# 7. Training settings
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    save_strategy="epoch",
    logging_steps=50,
)

# 8. Use a small subset for speed (full IMDb is 25,000 examples — very slow on free Colab)
small_train = tokenized_dataset["train"].shuffle(seed=42).select(range(2000))
small_eval  = tokenized_dataset["test"].shuffle(seed=42).select(range(500))

# 9. Trainer handles the actual training loop for you
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train,
    eval_dataset=small_eval,
)
trainer.train()

# 10. Save your fine-tuned model
model.save_pretrained("./my-finetuned-gpt2-sentiment")
tokenizer.save_pretrained("./my-finetuned-gpt2-sentiment")

README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

plain_text/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 21.0MB

plain_text/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

plain_text/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 20.5MB

plain_text/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

plain_text/unsupervised-00000-of-00001.p(…): reconstructing file:   0%|          |  0.00B / 42.0MB

plain_text/unsupervised-00000-of-00001.p(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] GPT2ForSequenceClassification LOAD REPORT from: gpt2
Key          | Status  |
-------------+---------+-
score.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./my-finetuned-gpt2-sentiment/tokenizer_config.json',
 './my-finetuned-gpt2-sentiment/tokenizer.json')



# Use Case-Specific Problems Solvable by Fine-tuning GPT-2 on Custom Documents

Fine-tuning GPT-2 on domain-specific documents enables organizations to create specialized text generation models that address unique business challenges. This report examines several concrete applications where GPT-2 fine-tuning provides effective solutions to industry-specific problems by leveraging custom datasets.

## Domain-Specific Text Generation Applications

### Medical Query Response Systems

The healthcare industry faces significant challenges in providing accessible medical information to patients. Fine-tuning GPT-2 on medical datasets creates specialized models like MedGPT-2 that can address these issues effectively.

MedGPT-2 demonstrates how fine-tuned models can provide accurate responses to medical queries, symptom descriptions, and mental health questions[^5]. This application involves collecting diverse medical datasets from forums and medical websites to train a model capable of generating informative responses to patient questions[^5]. Such systems can reduce the burden on healthcare professionals by serving as a first-line information resource, particularly in underserved areas where medical expertise may be limited.

The implementation process requires careful data collection, model fine-tuning, and integration with user-friendly interfaces like Streamlit for practical deployment[^5]. Future enhancements could include expanding datasets and implementing feedback mechanisms to improve answer quality over time[^5].

### Financial Advisory Services

Financial institutions often struggle to provide personalized advice at scale. Fine-tuned GPT-2 models offer a solution by generating tailored financial guidance based on customer queries.

A financial advice GPT-2 model, fine-tuned on financial datasets, can assist users with budgeting, investment strategies, and financial planning[^7]. This application addresses the need for accessible financial guidance outside traditional advisor relationships. The model leverages the transformer-based architecture of GPT-2 while focusing specifically on financial contexts[^7].

Such models can be integrated into larger financial advisory systems, chatbots, or automated customer service platforms to enhance the financial literacy of customers while reducing operational costs for financial institutions[^7].

### Customer Service Automation

Customer service departments frequently handle repetitive queries that could be automated with appropriate natural language processing systems.

Banking customer service chatbots developed through GPT-2 fine-tuning demonstrate how pre-trained language models can be adapted to specific customer service domains[^6]. By fine-tuning models like distilGPT-2 on banking-related queries and responses, organizations can create conversational AI systems that handle routine customer inquiries effectively[^6].

The implementation process involves tokenizing and preparing datasets, utilizing Hugging Face's Transformers library, and creating user interfaces with tools like Gradio[^6]. These systems can significantly reduce response times and operational costs while maintaining consistent service quality.

### Legal Document Generation

Law firms and legal departments face challenges in drafting standardized legal opinions efficiently while maintaining quality and consistency.

Fine-tuning GPT-2 on legal opinion datasets enables the generation of technical legal reports that follow established formats and incorporate appropriate legal terminology[^4]. This application addresses the time-intensive nature of legal drafting while potentially reducing costs for clients.

Such systems could serve as first-draft generators for attorneys, who would then review and refine the machine-generated content. This workflow maintains quality control while accelerating document production.

## Technical Approaches to Fine-Tuning

### Hierarchical Domain Adaptation

When dealing with related but distinct domains, hierarchical fine-tuning approaches offer advantages over single-domain methods.

Research shows that representing domains hierarchically allows models to capture both domain-specific and general-domain information[^3]. By using adapter layers to represent nodes in a hierarchical structure, models can selectively share representations between related domains while avoiding negative transfer from unrelated domains[^3].

This approach is particularly valuable when fine-tuning for multiple related domains, such as hotel reviews and restaurant reviews, which share some linguistic features but retain domain-specific characteristics[^3]. The hierarchical structure allows upper nodes to be updated more frequently, encoding more general knowledge, while leaf nodes capture domain-specific information[^3].

### Implementation Considerations

Implementing GPT-2 fine-tuning for custom applications involves several critical steps that ensure successful model development.

The process typically begins with installing dependencies and importing necessary libraries, including PyTorch and Hugging Face Transformers[^2]. Data processing involves splitting datasets into training and validation sets (typically 90% for training, 10% for validation)[^2]. Tokenization using the GPT-2 tokenizer prepares input and target sequences with appropriate padding and truncation options[^2].

Training configurations must specify parameters like output directory, number of training epochs, batch size, evaluation strategy, and logging frequency[^2]. After fine-tuning, the model can be saved and deployed for inference, with consideration given to computational resources like GPU availability for optimal performance[^2].

## Application Development Process

### Medical Query Assistant Development

Creating specialized applications like medical query assistants follows a structured process from data collection through deployment.

The development workflow begins with gathering diverse datasets of medical queries and responses from appropriate sources[^5]. After preprocessing the data, the GPT-2 model is fine-tuned using the prepared dataset to adapt it specifically to medical terminology and question-answering patterns[^5].

Following successful fine-tuning, the model is integrated with front-end frameworks like Streamlit to create user-friendly interfaces where users can enter medical queries and receive generated responses[^5]. Backend integration connects the interface to the fine-tuned model, allowing for seamless question processing and answer generation[^5].

### Banking Customer Service Implementation

Building customer service chatbots for specific industries like banking follows similar patterns but with domain-specific considerations.

The development process involves fine-tuning pre-trained models like distilGPT-2 on banking-related conversations and FAQs[^6]. Web-based interfaces created with tools like Gradio allow users to interact with the model through intuitive chat interfaces[^6].

These implementations enable financial institutions to provide 24/7 customer service while maintaining consistent response quality and reducing operational costs[^6].

## Conclusion

Fine-tuning GPT-2 on custom documents presents viable solutions to domain-specific challenges across multiple industries. From healthcare to finance, legal services to customer support, the ability to adapt pre-trained language models to specialized domains creates opportunities for automation, improved service delivery, and cost reduction.

The success of these applications depends on carefully selected training data, appropriate fine-tuning methodologies, and thoughtful integration into existing workflows. As organizations continue to explore the potential of fine-tuned language models, we can expect to see increasingly sophisticated applications that address more complex domain-specific problems.

Future developments will likely focus on improving model accuracy, expanding datasets to cover more diverse scenarios, and implementing feedback mechanisms that allow fine-tuned models to improve continuously through real-world use.


[^1]: https://platform.openai.com/docs/guides/fine-tuning

[^2]: https://github.com/arham-kk/gpt2-finetune

[^3]: https://blog.allenai.org/efficient-hierarchical-domain-adaptation-using-pretrained-language-models-fdd04c001230?gi=0c070ef42bb7

[^4]: https://community.openai.com/t/is-fine-tuning-the-way-to-go-to-generate-legal-opinions-law-technical-reports/170169

[^5]: https://github.com/Saish459/Finetuning-LLMs-MedGPT

[^6]: https://www.youtube.com/watch?v=_Pndmc__-v4

[^7]: https://huggingface.co/RoamifyMML/financial-advice-gpt2

[^8]: https://github.com/MehwishFatimah/GPT2_Summarization

[^9]: https://www.restack.io/p/fine-tuning-answer-gpt2-cat-ai

[^10]: https://30dayscoding.com/blog/gpt-for-named-entity-recognition-and-entity-extraction

[^11]: https://www.youtube.com/watch?v=nsdCRVuprDY

[^12]: https://community.openai.com/t/fine-tuning-gpt2-with-gpt4-responses-is-it-allowed/326740

[^13]: https://github.com/lizatukhtina/fine-tune-gpt2-for-meetiing-summarization

[^14]: https://www.toptal.com/deep-learning/exploring-pre-trained-models

[^15]: https://www.cohorte.co/blog/fine-tuning-gpt-2-with-hugging-face-transformers-a-complete-guide

[^16]: https://www.linkedin.com/pulse/fine-tuning-gpt-2-large-language-model-unlocking-its-adamson-mbcs

[^17]: https://drlee.io/fine-tuning-gpt-2-for-sentiment-analysis-94ebdd7b5b24

[^18]: https://blog.devgenius.io/fine-tuning-the-gpt-2-large-language-model-unlocking-its-full-potential-66e3a082ab9c?gi=4773a5eba121

[^19]: https://fxis.ai/edu/how-to-fine-tune-the-gpt-2-model-for-specific-tasks/

[^20]: https://www.youtube.com/watch?v=2bqjzUX9ssE

[^21]: https://ar5iv.labs.arxiv.org/html/2112.08718

[^22]: https://fxis.ai/edu/how-to-fine-tune-the-gpt-2-model-a-comprehensive-guide-2/

[^23]: https://github.com/vaddhiparthy/GPT

[^24]: https://www.restack.io/p/transfer-learning-answer-gpt2-transfer-learning-cat-ai

[^25]: https://fxis.ai/edu/how-to-fine-tune-gpt-2-a-step-by-step-guide/

[^26]: https://fxis.ai/edu/how-to-fine-tune-a-gpt-2-model-on-a-custom-dataset/

[^27]: http://arxiv.org/pdf/2112.08718.pdf

[^28]: https://openai.com/index/fine-tuning-gpt-2/

[^29]: https://www.linkedin.com/pulse/part-2a-fine-tuning-gpt-2-harry-potter-language-generation-mehta-3m7lc

[^30]: https://itnext.io/easily-build-your-own-gpt-from-scratch-using-aws-51811b6355d3

[^31]: https://www.restack.io/p/fine-tuning-gpt-2-answer-techniques-cat-ai

[^32]: https://www.toolify.ai/ai-news/mastering-gpt2-finetuning-python-guide-for-llm-finetuning-588131

[^33]: https://www.linkedin.com/pulse/legal-drafting-ai-putting-gpt-2-practical-use-sergii-shcherbak

[^34]: https://ouci.dntb.gov.ua/en/works/4OoXnJ24/

[^35]: https://deepdesk.com/blog/gpt-and-customer-service

[^36]: https://huggingface.co/RoamifyMML/financial-advice-gpt2/blob/46c97bb80d0a6d886e30748fa20d7d3d42ec3f58/README.md

[^37]: https://www.youtube.com/watch?v=oEpLMb5D_G0

[^38]: https://scholars.lib.ntu.edu.tw/entities/publication/329d6f25-8778-4bd9-a9ab-7d9952e29d53

[^39]: https://www.linkedin.com/posts/shakti-pawar_fundamentals-finetuning-gpt2-on-medical-activity-7251144314393677825-9Zul

[^40]: https://www.linkedin.com/posts/manoj-ajjakana_building-a-customer-service-chatbot-with-activity-7241433202525937665-j0kV

[^41]: https://blog.aryansingh.space/blog/Fine-Tuning-GPT-2-for-Financial-News-and-Analysis-Text-Generation

[^42]: https://github.com/Jayveersinh-Raj/code_generation_gpt2

[^43]: https://www.intel.com/content/www/us/en/developer/articles/training/fine-tuning-gpt2-with-hugging-face-and-intel-gaudi.html

[^44]: https://github.com/aymanehachcham/GPT2_Text_Summarization

[^45]: https://sohaib.com/how-to-use-gpt2-for-question-answering/

[^46]: https://30dayscoding.com/blog/fine-tuning-gpt-for-relation-extraction-and-knowledge-base-population

[^47]: https://discuss.huggingface.co/t/fine-tuning-gpt2-for-question-answering/31895

[^48]: https://arxiv.org/pdf/2309.06112.pdf

[^49]: https://www.linkedin.com/pulse/crafting-coherent-contextually-relevant-text-gpt-2-technical-arora-anfoc

[^50]: https://github.com/omidiu/GPT-2-Fine-Tuning

[^51]: https://www.youtube.com/watch?v=C_pWDlZWNIE

[^52]: https://github.com/arham-kk/gpt2-finetune

[^53]: https://discuss.huggingface.co/t/how-to-train-gpt-2-for-text-summarization/31731

[^54]: https://blog.paperspace.com/generating-text-summaries-gpt-2/

[^55]: https://www.restack.io/p/fine-tune-gpt2-answer-summarization-cat-ai

[^56]: https://www.cohorte.co/blog/fine-tuning-gpt-2-with-hugging-face-transformers-a-complete-guide

# Problems

Below are practical problems that can be addressed by fine-tuning GPT-2 on publicly available datasets, along with a brief overview of how to solve each using Google Colab.

---

### 1. Sentiment Analysis on Movie Reviews

**Problem:**  
Automatically classify movie reviews as positive or negative.

**Public Data:**  
IMDb movie reviews dataset (available via Hugging Face Datasets library).

**How to Solve:**
- Load the IMDb dataset using `datasets.load_dataset("imdb")`[3][5].
- Preprocess and tokenize the reviews using GPT-2’s tokenizer.
- Fine-tune GPT-2 (or GPT-2 for sequence classification) for 2–3 epochs on a Colab GPU instance.
- Evaluate the model and use it to predict sentiment for new reviews[3][5].

---

### 2. Domain-Specific Text Generation (e.g., Harry Potter Fan Fiction)

**Problem:**  
Generate creative text in the style of a specific domain, such as Harry Potter fan fiction.

**Public Data:**  
Fan fiction or book excerpts from Project Gutenberg or fan sites.

**How to Solve:**
- Gather and clean a collection of relevant text (e.g., Harry Potter books or fan fiction)[4].
- Tokenize the text using GPT-2’s tokenizer.
- Fine-tune GPT-2 for language modeling (text generation) for several epochs.
- Use the model to generate new domain-specific stories or paragraphs[4].

---

### 3. FAQ Answer Generation for a Public Dataset

**Problem:**  
Automatically generate answers to frequently asked questions in a specific domain (e.g., COVID-19 FAQs, Stack Overflow programming questions).

**Public Data:**  
- COVID-19 FAQ datasets from official sources.
- Stack Overflow question-answer pairs (public data dumps).

**How to Solve:**
- Collect question-answer pairs and clean the dataset[1].
- Format data as prompt-response pairs for GPT-2.
- Tokenize and fine-tune GPT-2 on these pairs.
- Use the model to generate answers to new, similar questions[1].

---

### 4. Headline Generation for News Articles

**Problem:**  
Generate concise headlines for news articles.

**Public Data:**  
CNN/DailyMail news dataset or other open news datasets.

**How to Solve:**
- Download and preprocess article-headline pairs.
- Tokenize the data and fine-tune GPT-2 to generate headlines given article snippets.
- Evaluate model outputs on a validation set.

---

### 5. Poetry or Song Lyric Generation

**Problem:**  
Generate poetry or song lyrics in a particular style.

**Public Data:**  
Poetry Foundation corpus, Project Gutenberg poetry, or song lyrics datasets.

**How to Solve:**
- Gather and clean a corpus of poems or lyrics.
- Tokenize and fine-tune GPT-2 for text generation.
- Prompt the model with a first line or theme to generate new poetic content.

---

## General Steps for Fine-Tuning on Google Colab

1. **Set Up Colab and Enable GPU:**  
   Open a new Colab notebook, enable GPU support[2].

2. **Install Required Libraries:**  
   Install `transformers`, `torch`, and `datasets`[2][3][5].

3. **Load and Preprocess Data:**  
   Use Hugging Face Datasets or upload your own data. Clean and tokenize the text[1][3][5].

4. **Load Pre-trained GPT-2 Model:**  
   Use `GPT2LMHeadModel` for generation or `GPT2ForSequenceClassification` for classification tasks[3][5].

5. **Fine-Tune the Model:**  
   Use Hugging Face’s `Trainer` or a custom training loop. Set epochs and batch size to fit within Colab’s memory and time constraints[3][5].

6. **Evaluate and Save the Model:**  
   Test the model on a validation set and save it to Google Drive or download it[2][3].

---


Citations:
[1] https://www.restack.io/p/fine-tuning-answer-gpt-2-models-cat-ai
[2] https://www.reddit.com/r/learnmachinelearning/comments/1fm6gif/is_it_possible_to_finetune_pretrained_models_like/
[3] https://drlee.io/fine-tuning-gpt-2-for-sentiment-analysis-94ebdd7b5b24
[4] https://www.linkedin.com/pulse/part-2a-fine-tuning-gpt-2-harry-potter-language-generation-mehta-3m7lc
[5] https://www.cohorte.co/blog/fine-tuning-gpt-2-with-hugging-face-transformers-a-complete-guide
[6] https://labelyourdata.com/articles/gpt-fine-tuning
[7] https://customgpt.ai/openai-gpt-fine-tuning-cases/
[8] https://github.com/DivyanshTiwari20/fine-tunning-GPT2LMHeadModel
[9] https://drlee.io/fine-tuning-gpt-2-for-sentiment-analysis-94ebdd7b5b24
[10] https://www.datacamp.com/tutorial/fine-tuning-large-language-models
[11] https://www.restack.io/p/fine-tuning-answer-gpt-2-cat-ai
[12] https://www.linkedin.com/pulse/part-2a-fine-tuning-gpt-2-harry-potter-language-generation-mehta-3m7lc
[13] https://www.restack.io/p/fine-tuning-gpt-2-answer-techniques-cat-ai
[14] https://github.com/arham-kk/gpt2-finetune
[15] https://gist.github.com/MattPitlyk/45541145ad48b93da395f0a72ec2e7dc?short_path=2ad537e
[16] https://colab.research.google.com/github/philschmid/fine-tune-GPT-2/blob/master/Fine_tune_a_non_English_GPT_2_Model_with_Huggingface.ipynb
[17] https://www.youtube.com/watch?v=2bqjzUX9ssE
[18] https://platform.openai.com/docs/guides/fine-tuning
[19] https://github.com/openai/gpt-2/issues/155
[20] https://www.youtube.com/watch?v=nsdCRVuprDY
[21] https://www.toptal.com/deep-learning/exploring-pre-trained-models
[22] https://www.youtube.com/watch?v=C_pWDlZWNIE
[23] https://www.toolify.ai/gpts/level-up-your-nlp-finetune-llama-2-model-with-free-colab-326769
[24] https://colab.research.google.com/drive/13dZVYEOMhXhkXWfvSMVM1TTtUDrT6Aeh?usp=sharing
[25] https://www.kaggle.com/code/changyeop/how-to-fine-tune-gpt-2-for-beginners
[26] https://stackoverflow.com/questions/74712335/how-to-fine-tune-a-gpt-2-model

Problem 1 — Sentiment Analysis on Movie Reviews

Step 1 — load and prepare the data:

In [1]:
from transformers import GPT2Tokenizer
from datasets import load_dataset

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token  # GPT-2 has no pad token by default

# Load IMDb dataset (note the updated namespace)
dataset = load_dataset("stanfordnlp/imdb")

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128)

tokenized_dataset = dataset.map(tokenize_function, batched=True)

# Use a small subset for speed on free Colab GPU
small_train = tokenized_dataset["train"].shuffle(seed=42).select(range(2000))
small_eval  = tokenized_dataset["test"].shuffle(seed=42).select(range(500))

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

plain_text/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 21.0MB

plain_text/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

plain_text/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 20.5MB

plain_text/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

plain_text/unsupervised-00000-of-00001.p(…): reconstructing file:   0%|          |  0.00B / 42.0MB

plain_text/unsupervised-00000-of-00001.p(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

Step 2 — fine-tune GPT-2 for classification:

In [2]:
from transformers import GPT2ForSequenceClassification, TrainingArguments, Trainer

model = GPT2ForSequenceClassification.from_pretrained("gpt2", num_labels=2)
model.config.pad_token_id = tokenizer.pad_token_id

training_args = TrainingArguments(
    output_dir="./results-sentiment",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    save_strategy="epoch",
    logging_steps=50,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train,
    eval_dataset=small_eval,
)
trainer.train()

model.save_pretrained("./my-finetuned-gpt2-sentiment")
tokenizer.save_pretrained("./my-finetuned-gpt2-sentiment")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] GPT2ForSequenceClassification LOAD REPORT from: gpt2
Key          | Status  |
-------------+---------+-
score.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./my-finetuned-gpt2-sentiment/tokenizer_config.json',
 './my-finetuned-gpt2-sentiment/tokenizer.json')

Step 3 — evaluate and use the model to predict new reviews:

In [3]:
from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="./my-finetuned-gpt2-sentiment",
    tokenizer=tokenizer
)

# Try it on new, unseen text
print(classifier("This movie was surprisingly touching and well written."))
print(classifier("Total waste of time, I almost fell asleep."))

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

[{'label': 'LABEL_1', 'score': 0.994155764579773}]
[{'label': 'LABEL_0', 'score': 0.9983521699905396}]

Problem 2 — Domain-Specific Text Generation (e.g. Harry Potter fan fiction)

Step 1 — get text data.

In [ ]:
sample_text = """
Harry looked up at the castle, its towers glowing under the pale moon...
Hermione flipped through the ancient book, searching for the answer...
"""  # replace with real, larger text — a few thousand words minimum for real results

with open("domain_text.txt", "w") as f:
    f.write(sample_text)

Step 2 — full fine-tuning code:

In [ ]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel, TrainingArguments, Trainer, DataCollatorForLanguageModeling
from datasets import load_dataset

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained("gpt2")

# Load your own text file as a dataset
dataset = load_dataset("text", data_files={"train": "domain_text.txt"})

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128)

tokenized_dataset = dataset.map(tokenize_function, batched=True)

# Language modeling needs a data collator that creates "labels" automatically
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./results-domain",
    num_train_epochs=5,
    per_device_train_batch_size=2,
    save_strategy="epoch",
    logging_steps=10,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    data_collator=data_collator,
)
trainer.train()

model.save_pretrained("./my-finetuned-gpt2-domain")
tokenizer.save_pretrained("./my-finetuned-gpt2-domain")

# Generate new text in that style
from transformers import pipeline
generator = pipeline("text-generation", model="./my-finetuned-gpt2-domain", tokenizer=tokenizer)
print(generator("Harry looked", max_length=50, num_return_sequences=1)[0]["generated_text"])

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/3 [00:00<?, ? examples/s]

[transformers] `loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Harry looked up at the stars.

"In the dark, in the night, in the void..."

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Problem 3 — FAQ Answer Generation

Step 1 — format your data as Q/A pairs in a text file:

In [ ]:
qa_pairs = """Q: What is COVID-19?
A: COVID-19 is a respiratory illness caused by the SARS-CoV-2 virus.

Q: How does it spread?
A: It spreads mainly through respiratory droplets from coughing or sneezing.
"""
with open("faq_text.txt", "w") as f:
    f.write(qa_pairs)

Step 2 — fine-tuning

In [ ]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel, TrainingArguments, Trainer, DataCollatorForLanguageModeling
from datasets import load_dataset

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained("gpt2")

dataset = load_dataset("text", data_files={"train": "faq_text.txt"})

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128)

tokenized_dataset = dataset.map(tokenize_function, batched=True)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./results-faq",
    num_train_epochs=5,
    per_device_train_batch_size=2,
    save_strategy="epoch",
    logging_steps=10,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    data_collator=data_collator,
)
trainer.train()

model.save_pretrained("./my-finetuned-gpt2-faq")
tokenizer.save_pretrained("./my-finetuned-gpt2-faq")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Map:   0%|          | 0/5 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./my-finetuned-gpt2-faq/tokenizer_config.json',
 './my-finetuned-gpt2-faq/tokenizer.json')

Step 3 — generate an answer to a new question:

In [ ]:
prompt = "Q: Can I get COVID-19 twice?\nA:"
print(generator(prompt, max_length=60, num_return_sequences=1)[0]["generated_text"])

[transformers] Both `max_new_tokens` (=256) and `max_length`(=60) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: Can I get COVID-19 twice?
A: No, I'll just need to follow up on the last question. I'm asking you if we'll be able to get him to go back to the camp.
Q: Can I get COVID-19 twice?
A: No, I'll just need to follow up on the last question. I'm asking you if we'll be able to get him to go back to the camp.
Q: Can I get COVID-19 twice?
A: No, I'll just need to follow up on the last question. I'm asking you if we'll be able to get him to go back to the camp.
Q: Can I get COVID-19 twice?
A: No, I'll just need to follow up on the last question. I'm asking you if we'll be able to get him to go back to the camp.
Q: Can I get COVID-19 twice?
A: No, I'll just need to follow up on the last question. I'm asking you if we'll be able to get him to go back to the camp.
Q: Can I get COVID-19 twice?
A: No, I'll just need to follow up on the last question. I'm

Problem 4 — Headline Generation for News Articles

Step 1 — format data as "Article: ... \nHeadline: ..." pairs:

In [ ]:
article_data = """Article: Scientists discovered a new species of frog in the Amazon rainforest during a recent expedition.
Headline: New Frog Species Discovered in Amazon

Article: The city council approved funding for three new public parks next year.
Headline: City Council Approves Funding for New Parks
"""
with open("headline_text.txt", "w") as f:
    f.write(article_data)

Step 2 — fine-tuning

In [ ]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel, TrainingArguments, Trainer, DataCollatorForLanguageModeling
from datasets import load_dataset

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained("gpt2")

dataset = load_dataset("text", data_files={"train": "headline_text.txt"})

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128)

tokenized_dataset = dataset.map(tokenize_function, batched=True)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./results-headline",
    num_train_epochs=5,
    per_device_train_batch_size=2,
    save_strategy="epoch",
    logging_steps=10,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    data_collator=data_collator,
)
trainer.train()

model.save_pretrained("./my-finetuned-gpt2-headline")
tokenizer.save_pretrained("./my-finetuned-gpt2-headline")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/5 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./my-finetuned-gpt2-headline/tokenizer_config.json',
 './my-finetuned-gpt2-headline/tokenizer.json')

Step 3 — generate a headline for a new article:

In [ ]:
prompt = "Article: Local school district announced a new STEM program for high schoolers.\nHeadline:"
print(generator(prompt, max_length=40, num_return_sequences=1)[0]["generated_text"])

[transformers] Both `max_new_tokens` (=256) and `max_length`(=40) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Article: Local school district announced a new STEM program for high schoolers.
Headline: Houston, TX - September 26, 2018 - A new school district announced a new STEM program for high schoolers.
Houston Chronicle Staff Writer The Chronicle's John Kugler (Photo: John Kugler)

In the beginning, there was a girl in the back of the school, one that went to high school with her sister. She was a science student at the time. "When I told my sister, she's such a cool person, it was like, 'Why did you ask about that?'"

Her sister, who's now a science student at Texas A&M University, is a science major. She says, "I'm not interested in science. I'm interested in technology." The girl had a dream of becoming a doctor. "But when you're in high school, you're not taught about science, you're not taught about technology."

She's right. STEM is new, innovative, and exciting. But it's atypical for a school district to focus on one area of its schools' needs, with the hopes of increasing STEM participation.

"The thing is, you don't want to go to a high school and be a computer programmer, you want to go to the college and to the university

Problem 5 — Poetry or Song Lyric Generation

Step 1 — create your poems/lyrics file:

In [ ]:
poems_text = """The stars above whisper secrets untold,
While the moonlight dances on rivers of gold.
The wind hums a tune through the silver birch trees,
Carrying whispers of love on the breeze.

Beneath the wide sky where the wild things roam,
The heart finds its way, and the heart finds its home.
Through shadows and sunlight, through storm and through calm,
The soul sings its verses like a quiet psalm.
"""
with open("poems_text.txt", "w") as f:
    f.write(poems_text)

Step 2 — fine-tuning code:

In [ ]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel, TrainingArguments, Trainer, DataCollatorForLanguageModeling
from datasets import load_dataset

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained("gpt2")

dataset = load_dataset("text", data_files={"train": "poems_text.txt"})

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128)

tokenized_dataset = dataset.map(tokenize_function, batched=True)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./results-poems",
    num_train_epochs=5,
    per_device_train_batch_size=2,
    save_strategy="epoch",
    logging_steps=10,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    data_collator=data_collator,
)
trainer.train()

model.save_pretrained("./my-finetuned-gpt2-poems")
tokenizer.save_pretrained("./my-finetuned-gpt2-poems")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/9 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./my-finetuned-gpt2-poems/tokenizer_config.json',
 './my-finetuned-gpt2-poems/tokenizer.json')

Step 3 — generate with an opening line:

In [ ]:
from transformers import pipeline
generator = pipeline("text-generation", model="./my-finetuned-gpt2-poems", tokenizer=tokenizer)

prompt = "The stars above whisper"
print(generator(prompt, max_length=50, num_return_sequences=1)[0]["generated_text"])

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

The stars above whisper secrets of pleasure and magic.

The stars above whisper secrets of pleasure and magic.

The stars above whisper secrets of pleasure and magic.

A heart sings with the love of its home, and the heart sings with the love of its home.

A heart sings with the love of its home, and the heart sings with the love of its home.

A heart sings with the love of its home, and the heart sings with the love of its home.

A heart sings with the love of its home, and the heart sings with the love of its home.

A heart sings with the love of its home, and the heart sings with the love of its home.

A heart sings with the love of its home, and the heart sings with the love of its home.

A heart sings with the love of its home, and the heart sings with the love of its home.

A heart sings with the love of its home, and the heart sings with the love of its home.

A heart sings with the love of its home, and the heart sings with the love of its home.

A heart sings with the love of its home, and the heart sings with the love